# Documentation:
# https://trovu.net/docs/users/advanced/#custom-configuration
namespaces:
- o
- en
- .uk
- .gb
- github: 4mel1a
  name: ari
- github: .
  name: my

defaultKeyword: s
language: en
country: gb
